### ISSUE TITLE
Always plays the same radio source

### ISSUE THREAD

**Issue by GuillaumeHM** [fossfreedom/remember-the-rhythm#5]
Hello, 
The plugin seems to have worked one time at least because it now always plays the same (radio) source at startup. And it don't saves the last source or even the play state.

Here is the trace I have : 

```
$ rhythmbox

(rhythmbox:24664): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(rhythmbox:24664): libsoup-CRITICAL **: soup_server_quit: assertion 'priv->listeners != NULL' failed
sys:1: Warning: object SoupServer 0x2059770 finalized while still in-construction
sys:1: Warning: Custom constructor for class SoupServer returned NULL (which is invalid). Please use GInitable instead.
sys:1: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.

(rhythmbox:24664): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:24664): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:24664): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:24664): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:24664): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture


(rhythmbox:24664): Gtk-WARNING **: Duplicate child name in GtkStack: Ajouter à la liste de lecture

Traceback (most recent call last):
  File "/home/gui/.local/share/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 185, in init_source
    self.shell_player.jump_to_current()
GLib.Error: g-invoke-error-quark: Could not locate rb_shell_player_jump_to_current: 'rb_shell_player_jump_to_current': /usr/lib/librhythmbox-core.so.9: undefined symbol: rb_shell_player_jump_to_current (1)
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/artsearch/local.py", line 129, in _enum_children_cb
    enumfiles = parent.enumerate_children_finish(result)
GLib.Error: g-io-error-quark: Opération non prise en charge par le moteur (15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/artsearch/local.py", line 136, in _enum_children_cb
    self.callback(self.callback_args)
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 59, in search_done
    self.next_search()
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 55, in next_search
    search.search(self.key, self.last_time, self.store, self.search_done, None)
  File "/usr/lib/rhythmbox/plugins/artsearch/musicbrainz.py", line 111, in search
    self.try_search_artist_album(key, store, callback, args)
  File "/usr/lib/rhythmbox/plugins/artsearch/musicbrainz.py", line 97, in try_search_artist_album
    callback(*args)
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 59, in search_done
    self.next_search()
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 55, in next_search
    search.search(self.key, self.last_time, self.store, self.search_done, None)
  File "/usr/lib/rhythmbox/plugins/artsearch/lastfm.py", line 156, in search
    callback (args)
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 59, in search_done
    self.next_search()
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 49, in next_search
    key = RB.ExtDBKey.create_storage("album", self.key.get_field("album"))
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/home/gui/.local/share/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 96, in pause
    print(self.shell_player.set_playing_time(time))
GLib.Error: rb_shell_player_error: Le morceau actuel ne peut pas être parcouru (3)

(rhythmbox:24664): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed
Traceback (most recent call last):
  File "/home/gui/.local/share/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 185, in init_source
    self.shell_player.jump_to_current()
GLib.Error: g-invoke-error-quark: Could not locate rb_shell_player_jump_to_current: 'rb_shell_player_jump_to_current': /usr/lib/librhythmbox-core.so.9: undefined symbol: rb_shell_player_jump_to_current (1)
^Z
```

Please note the error "undefined symbol: rb_shell_player_jump_to_current".

**Comment by fossfreedom** [comment]
what version of rhythmbox are you using?

**Comment by GuillaumeHM** [comment]
3.2.1, on debian Stretch 64 bit.

**Comment by fossfreedom** [comment]
ok - thanks.

There is a definite bug in rhythmbox where "jump-to-current" suddenly becomes an invalid function for radio-sources.

radio-sources dont seem to register correctly with the plugin.  The plugin works ok with standard music tracks.

**Comment by GuillaumeHM** [comment]
OK, the bug is a bit more complicated.
The plugins registers the last source if the previous one was not a radio.

Play a music file
Play a web radio A
Close RB.
Open RB -> it correctly plays the last source (radio A)
Play Radio B
Close RB
OpenRB -> It wrongly plays Radio A
Play a music file
Play Radio B
Cose RB
Open RB -> It correctly plays Radio B

I think the jump-to-current problem is another issue, do you confirm ?

**Comment by fossfreedom** [comment]
jump-to-current errors messes with the saving.  

But yes - once commented out, this leaves an underlying issue with handling radio-streams.

**Comment by fossfreedom** [comment]
@GuillaumeHM  - think the above commit fixes this.  Can you give this a try please?

**Comment by GuillaumeHM** [comment]
Works perfectly fine, thank you very much ! And I don't have the crash around jump_to_current anymore.

**Comment by fossfreedom** [comment]
ta for testing.

I've done some small tweaks to get the pause & play/pause on startup options in preferences working correctly.

I'll close this now.  Cheers.

**Comment by GuillaumeHM** [comment]
Play/Pause feature works fine now but I have a small moment when audio is played before being muted at startup.

**Comment by fossfreedom** [comment]
yep - nothing I can really do about that.  Rhythmbox itself doesnt offer a way to mute BEFORE playing - you can only mute AFTER playing.

I could in theory use pulseaudio to turn off the sound but that  would mean introducing python3-pulseaudio - its not in current distro's so it will mean making people install this manually.  Thus this will dissuade people from installing the plugin.
